### ISSUE TITLE
(LEX) Properly resolve invalid identifiers/keywords

### ISSUE THREAD

**Issue by as577** [as577/tiger-compiler#35]
According to Drew's answer here: https://piazza.com/class/ixta4v2cctu2bn?cid=43

**Comment by narendly** [comment]
I think both should evaluate to invalid identifiers per Tiger spec manual. A lot of other languages allow identifiers to have an underscore but Tiger manual says:
-------
Identifiers (id and tyId): An identifier **starts with
a letter**, followed by zero or more letters, underscores,
or digits. Keywords cannot be used as identifiers.
Identifiers are case-sensitive.
-------
